//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationTypeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationTypeMaster()
        {
            this.ApplicationMasters = new HashSet<ApplicationMaster>();
            this.ApplicationTypeDevieTypeMasters = new HashSet<ApplicationTypeDevieTypeMaster>();
            this.TransactionApplicationTypeMappingMasters = new HashSet<TransactionApplicationTypeMappingMaster>();
        }
    
        public int ID { get; set; }
        public string ApplicationTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationMaster> ApplicationMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationTypeDevieTypeMaster> ApplicationTypeDevieTypeMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionApplicationTypeMappingMaster> TransactionApplicationTypeMappingMasters { get; set; }
    }
}
