//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationProjectMappingMaster
    {
        public int ID { get; set; }
        public int ApplicationID { get; set; }
        public int ProjectID { get; set; }
    
        public virtual ApplicationMaster ApplicationMaster { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
    }
}
