//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationMaster()
        {
            this.ApplicationProjectMappingMasters = new HashSet<ApplicationProjectMappingMaster>();
        }
    
        public int ID { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationDesc { get; set; }
        public string AuthToken { get; set; }
        public int ApplicationTypeID { get; set; }
    
        public virtual ApplicationTypeMaster ApplicationTypeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationProjectMappingMaster> ApplicationProjectMappingMasters { get; set; }
    }
}
