//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CameraPositionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CameraPositionMaster()
        {
            this.CameraDtlsTbls = new HashSet<CameraDtlsTbl>();
            this.DamageTransactionDetails = new HashSet<DamageTransactionDetail>();
        }
    
        public int PositionID { get; set; }
        public string PositionName { get; set; }
        public string PositionDescription { get; set; }
        public int ContainerVisible { get; set; }
        public Nullable<int> ImageIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CameraDtlsTbl> CameraDtlsTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DamageTransactionDetail> DamageTransactionDetails { get; set; }
    }
}
