//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CameraDtlsTbl
    {
        public int CameraID { get; set; }
        public string CameraIP { get; set; }
        public int LaneID { get; set; }
        public int PositionID { get; set; }
        public bool Active { get; set; }
    
        public virtual CameraPositionMaster CameraPositionMaster { get; set; }
        public virtual LaneMaster LaneMaster { get; set; }
    }
}
