//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageTransactionDetail
    {
        public long ID { get; set; }
        public int DmgDtlsID { get; set; }
        public string DamageRemark { get; set; }
        public Nullable<int> CamPosID { get; set; }
        public string DamageTypes { get; set; }
        public bool IsCommonRemark { get; set; }
    
        public virtual CameraPositionMaster CameraPositionMaster { get; set; }
        public virtual DamageTransaction DamageTransaction { get; set; }
    }
}
