//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DamageTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DamageTransaction()
        {
            this.ContainerTransactions = new HashSet<ContainerTransaction>();
            this.DamageTransactionDetails = new HashSet<DamageTransactionDetail>();
        }
    
        public int DmgDtlsID { get; set; }
        public string RemarkCam1 { get; set; }
        public string RemarkCam2 { get; set; }
        public string RemarkCam3 { get; set; }
        public string RemarkCam4 { get; set; }
        public string RemarkCam5 { get; set; }
        public string RemarkCam6 { get; set; }
        public string RemarkCam7 { get; set; }
        public string CommonRemark { get; set; }
        public string DmgdTypeCam1 { get; set; }
        public string DmgdTypeCam2 { get; set; }
        public string DmgdTypeCam3 { get; set; }
        public string DmgdTypeCam4 { get; set; }
        public string DmgdTypeCam5 { get; set; }
        public string DmgdTypeCam6 { get; set; }
        public string DmgdTypeCam7 { get; set; }
        public string CommonDmgTypes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContainerTransaction> ContainerTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DamageTransactionDetail> DamageTransactionDetails { get; set; }
    }
}
