//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceMaster()
        {
            this.LaneDeviceMappingMasters = new HashSet<LaneDeviceMappingMaster>();
        }
    
        public int ID { get; set; }
        public string DeviceName { get; set; }
        public int DeviceTypeID { get; set; }
        public string DeviceIP { get; set; }
        public string DeviceMACAddress { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DeviceTypeMaster DeviceTypeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaneDeviceMappingMaster> LaneDeviceMappingMasters { get; set; }
    }
}
