//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceTypeMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeviceTypeMaster()
        {
            this.ApplicationTypeDevieTypeMasters = new HashSet<ApplicationTypeDevieTypeMaster>();
            this.DeviceMasters = new HashSet<DeviceMaster>();
            this.DeviceTypeDetailsMasters = new HashSet<DeviceTypeDetailsMaster>();
            this.LocationTypeDeviceTypeMappingMasters = new HashSet<LocationTypeDeviceTypeMappingMaster>();
        }
    
        public int ID { get; set; }
        public string DeviceTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationTypeDevieTypeMaster> ApplicationTypeDevieTypeMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceMaster> DeviceMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeviceTypeDetailsMaster> DeviceTypeDetailsMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocationTypeDeviceTypeMappingMaster> LocationTypeDeviceTypeMappingMasters { get; set; }
    }
}
