//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaneDeviceMappingMaster
    {
        public int ID { get; set; }
        public int LaneID { get; set; }
        public int DeviceID { get; set; }
    
        public virtual DeviceMaster DeviceMaster { get; set; }
        public virtual LaneMaster LaneMaster { get; set; }
    }
}
