//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaneMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaneMaster()
        {
            this.CameraDtlsTbls = new HashSet<CameraDtlsTbl>();
            this.ContainerTransactions = new HashSet<ContainerTransaction>();
            this.LaneDeviceMappingMasters = new HashSet<LaneDeviceMappingMaster>();
        }
    
        public int LaneID { get; set; }
        public int TypeOfGate { get; set; }
        public string LaneName { get; set; }
        public Nullable<int> CreatorUserID { get; set; }
        public bool TransactionsEnabled { get; set; }
        public Nullable<bool> IsBusy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CameraDtlsTbl> CameraDtlsTbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContainerTransaction> ContainerTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaneDeviceMappingMaster> LaneDeviceMappingMasters { get; set; }
    }
}
