//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectMaster()
        {
            this.ApplicationProjectMappingMasters = new HashSet<ApplicationProjectMappingMaster>();
        }
    
        public int ID { get; set; }
        public string ProjectName { get; set; }
        public int DeployerFirm { get; set; }
        public int DeployeeFirm { get; set; }
        public int TypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationProjectMappingMaster> ApplicationProjectMappingMasters { get; set; }
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual CompanyMaster CompanyMaster1 { get; set; }
        public virtual ProjectTypeMaster ProjectTypeMaster { get; set; }
    }
}
