//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleDesignationMappingMaster
    {
        public int ID { get; set; }
        public int DesignationID { get; set; }
        public int RoleID { get; set; }
    
        public virtual DesignationMaster DesignationMaster { get; set; }
        public virtual RoleMaster RoleMaster { get; set; }
    }
}
