//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingLineMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShippingLineMaster()
        {
            this.ContainerTransactions = new HashSet<ContainerTransaction>();
        }
    
        public int ShippingLineID { get; set; }
        public string ShippingLineName { get; set; }
        public string CompanyAddress { get; set; }
        public string ContactNo { get; set; }
        public string faxno { get; set; }
        public string emailid1 { get; set; }
        public string emailid2 { get; set; }
        public string emailid3 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContainerTransaction> ContainerTransactions { get; set; }
    }
}
