//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIMSContainerDBEFDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionFieldMaster
    {
        public int ID { get; set; }
        public int TransactionID { get; set; }
        public string TransactionFieldName { get; set; }
        public string TransactionFieldType { get; set; }
        public bool IsForeignKey { get; set; }
        public string ForeignKeyTableName { get; set; }
        public string ForeignKeyColumnName { get; set; }
    
        public virtual TransactionMaster TransactionMaster { get; set; }
    }
}
